version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vuepress/plugin-google-analytics"
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: vuepress
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: vuepress-theme-reco
    versions:
    - 1.6.1
    - 1.6.4
  - dependency-name: vue-class-component
    versions:
    - 7.2.6
